baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ventus'

disableKinds = ["taxonomy", "term", "RSS"]
ignoreErrors = ["error-disable-taxonomy"]

# allows hugo to access binaries installed with the ASDF version manager
# if this isn't set, hugo can't run node packages like postcss
[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$','^ASDF_DIR$', '^HOME$']

# allows hugo to access environment variables set by various hosting tools
[security.funcs]
getenv = ["^HUGO_", "^NETLIFY_", "^VERCEL_", "NODE_"]

[markup.goldmark.renderer]
unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min      = "v0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "index\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"